language: ruby
rvm:
- 2.1.0
env:
  global:
  - GIT_COMMITTER_NAME=nacyot
  - GIT_COMMITTER_EMAIL=propellerheaven@gmail.com
  - GIT_AUTHOR_NAME=nacyot
  - GIT_AUTHOR_EMAIL=propellerheaven@gmail.com
  - secure: jmBBlXbhNyWxQD9VJ4uPw8YTGW2vJPqAcq25Onxvr9e1P2Ls2aVi0XQB5bjcEpOUPaeO3oUWH4sAixQPOf3apvDUClAmkqU77izcAp+kKSkAOWr0Ggz+huu2SGKp0uxG8BVOk0V4F2/sDzTroVKqjmE7cFXmcaVDca3tR/NYSG0=
before_install:
- sudo apt-get install -qq libicu-dev
before_script:
- npm install -g bower
- bower install
- git clone https://github.com/nacyot/nacyot.com.git build
- cd build
- git checkout gh-pages
- cd ..
script: bundle exec middleman build --verbose
after_success:
- cd build
- git add -A
- git commit -m 'Update build files'
- git push --quiet https://$GH_TOKEN@github.com/nacyot/nacyot.com.git gh-pages
